version: 2

# references:
#   node-10: &node-10
#     working_directory: ~/splitshare
#     docker:
#       - image: circleci/node:10

#   restore-cache: $restore-cache
#       key: deps1-{{ .Branch }}-{{ checksum "yarn.lock" }}

#   save-cache: $save-cache
#       key: deps1-{{ .Branch }}-{{ checksum "yarn.lock" }}
#         paths:
#           - ./node_modules

#   yarn: $yarn
#     name: Install Dependencies
#     command: yarn install --pure-lockfile --frozen-lockfile

# lint: $lint

jobs:
  build:
    working_directory: ~/splitshare
    docker:
      - image: circleci/node:10
        environment:
          NODE_ENV: production
          DATABASE_URL: postgresql://ubuntu@localhost/splitshare-test?sslmode=disable
      - image: circleci/postgres:9.6.9
        environment:
          POSTGRES_USER: ubuntu
          POSTGRES_DB: splitshare-test
          POSTGRES_PASSOWRD: ''
    steps:
      - checkout
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "yarn.lock" }}
      - run:
          name: Instsall dependencies
          command: yarn install
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules

workflows:
  version: 2
  build:
    jobs:
      - build
