// export const userState = {
//   ONBOARDING_VERIFY_EMAIL: 'ONBOARDING_VERIFY_EMAIL',
//   ONBOARDING_PROFILE: 'ONBOARDING_PROFILE',
//   ACTIVE: 'ACTIVE',
// };

export enum UserState {
  ONBOARDING_VERIFY_EMAIL = 'ONBOARDING_VERIFY_EMAIL',
  ONBOARDING_PROFILE = 'ONBOARDING_PROFILE',
  ACTIVE = 'ACTIVE',
}
