# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Server

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test_and_build:
    name: Test and build server
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v1.4.2
      - name: Cache Node.js modules
        uses: actions/cache@v1
        with:
          path: ~/.npm # npm cache files are stored in `~/.npm` on Linux/macOS
          key: ${{ runner.OS }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-node-
            ${{ runner.OS }}-
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Build server
        working-directory: ./packages/server
        run: yarn build
      - name: Upload server files
        uses: actions/upload-artifact@v1
        with:
          name: server
          path: ./packages/server/dist

  dockerize:
    name: Build and publish docker image
    runs-on: ubuntu-latest
    needs: [test_and_build]

    steps:
      - uses: actions/checkout@v2
      - name: Download compiled server files
        uses: actions/download-artifact@v1
        with:
          name: server
          path: ./packages/server/dist
      - name: Build docker image
        working-directory: ./packages/server
        run: docker --version && yarn docker:build
      - name: Publish docker image
        run: |
          docker login --username ${{ secrets.DOCKER_USERNAME }} --password '${{ secrets.DOCKER_PASSWORD }}'
          docker push samuherek/splitshare:latest
