# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Web

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test_and_build:
    name: Test and build web
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v1.4.2
      - name: Cache Node.js modules
        uses: actions/cache@v1
        with:
          path: ~/.npm # npm cache files are stored in `~/.npm` on Linux/macOS
          key: ${{ runner.OS }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-node-
            ${{ runner.OS }}-
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Setup env varialbes
        working-directory: ./packages/web
        run: |
          touch .env
          echo 'REACT_APP_API_BASE_URL=https://api.splitshare.me' >> ./.env
          echo 'REACT_APP_AUTH0_CLIENT_ID=7A42PzX6beUckMoH60ieIsY2S8MlhOPV' >> ./.env
          echo 'REACT_APP_AUTH0_DOMAIN=https://splitshare.eu.auth0.com' >> ./.env
          echo 'REACT_APP_AUTH0_AUDIENCE=graphql' >> ./.env
          echo 'REACT_APP_AUTH0_LOGOUT_URL=https://splitshare.me' >> ./.env
      - name: Build web
        working-directory: ./packages/web
        run: yarn build --production
      - name: Upload web files
        uses: actions/upload-artifact@v1
        with:
          name: web
          path: ./packages/web/build

  notlify:
    name: Publish web to netlify
    runs-on: ubuntu-latest
    needs: [test_and_build]
    
    steps: 
      - name: Download compiled web files
        uses: actions/download-artifact@v1
        with:
          name: web
          path: ./build
      - name: Install netlify CLI
        run: sudo npm i -g netlify-cli
      - name: Deploy to netlify
        run: netlify deploy --dir=./build --prod
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
